task 5
jharold555/nc-news pull request #5
Opened 2023-08-16 09:31 UTC by jharold555

2023-08-16 11:06 UTC, Keb84 requested changes
Nice work so far 🎸 please check my comments and make the changes the resubmit your PR 🙂

2023-08-16 11:06 UTC, Keb84 commented on db/models.js
> +};
You should be make use of queries to the database in order to achieve the comment count. Have a look at aggregate functions in the sql relationships on nc notes on how to do this 👀

2023-08-16 11:06 UTC, Keb84 commented on db/models.js
> +  const comments = await db.query("SELECT * FROM comments;");
You should keep things consistent. If you are using async await you should do this all the way through.

2023-08-17 08:27 UTC, 2202Hannah requested changes
Nice work so far, I have made some comments on your test file. Please update you code and submit another pull request when you are ready.

2023-08-17 08:27 UTC, 2202Hannah commented on __tests__/app.test.js
> +    });
The article objects should also include topic, article_img_url, created_at and votes. Please make sure you are checking for these too. 
You can also check that the data type of each property is as expected by using a matcher function and expect.any(String).

2023-08-17 09:17 UTC, Keb84 approved these changes
Nice work 🤸 merge when ready 🙂

2023-08-17 10:47 UTC, merged

2023-08-17 11:01 UTC, Hard-Luck reviewed
I know this is already merged but there is a couple of things to check here

2023-08-17 11:01 UTC, Hard-Luck commented on __tests__/app.test.js
> +    expect(response.body.msg).toBe("404 username of bob Not Found");
I think this is more so a 400 as you would be trying to make a post with a user that doesn't exist so it would be a bad request rather than you looking for a resource that doesn't exist.

2023-08-17 11:01 UTC, Hard-Luck commented on __tests__/app.test.js
> +    await request(app)
here you should return the posted comment from your controller so you should be able to check it using const postedCommet = await request(app).post...
and access it that way